// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RESTWebApiCodeFirst.Data;

#nullable disable

namespace RESTWebApiCodeFirst.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RESTWebApiCodeFirst.Entities.ComponentManufacturers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "INT",
                            FoundationDate = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateTime(1969, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "AMD"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NV",
                            FoundationDate = new DateTime(1993, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "NVIDIA"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "SMS",
                            FoundationDate = new DateTime(1938, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Samsung"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "CRS",
                            FoundationDate = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Corsair"
                        });
                });

            modelBuilder.Entity("RESTWebApiCodeFirst.Entities.ComponentTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Memory"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "SSD",
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "PSU",
                            Name = "Power Supply"
                        });
                });

            modelBuilder.Entity("RESTWebApiCodeFirst.Entities.Components", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ComponentManufacturersId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturersId");

                    b.HasIndex("ComponentTypesId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "CPU001",
                            ComponentManufacturersId = 1,
                            ComponentTypesId = 1,
                            Description = "8-core processor",
                            Name = "Intel i7"
                        },
                        new
                        {
                            Code = "GPU001",
                            ComponentManufacturersId = 3,
                            ComponentTypesId = 2,
                            Description = "Gaming GPU",
                            Name = "RTX 4070"
                        },
                        new
                        {
                            Code = "RAM001",
                            ComponentManufacturersId = 4,
                            ComponentTypesId = 3,
                            Description = "Memory module",
                            Name = "16GB DDR4"
                        },
                        new
                        {
                            Code = "SSD001",
                            ComponentManufacturersId = 4,
                            ComponentTypesId = 4,
                            Description = "Fast storage",
                            Name = "1TB SSD"
                        },
                        new
                        {
                            Code = "PSU001",
                            ComponentManufacturersId = 5,
                            ComponentTypesId = 5,
                            Description = "Power supply",
                            Name = "750W PSU"
                        });
                });

            modelBuilder.Entity("RESTWebApiCodeFirst.Entities.PCComponents", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "CPU001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "GPU001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "CPU001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "RAM001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "SSD001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "RAM001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 4,
                            ComponentCode = "CPU001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 4,
                            ComponentCode = "GPU001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 5,
                            ComponentCode = "PSU001",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("RESTWebApiCodeFirst.Entities.PCs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X1",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 3.2f
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Pro 200",
                            Stock = 15,
                            Warranty = 24,
                            Weight = 2.1f
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "UltraBook Slim Z",
                            Stock = 8,
                            Warranty = 12,
                            Weight = 1.3f
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Workstation Titan",
                            Stock = 3,
                            Warranty = 48,
                            Weight = 4.5f
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Home Basic PC",
                            Stock = 20,
                            Warranty = 18,
                            Weight = 2.8f
                        });
                });

            modelBuilder.Entity("RESTWebApiCodeFirst.Entities.Components", b =>
                {
                    b.HasOne("RESTWebApiCodeFirst.Entities.ComponentManufacturers", "ComponentManufacturers")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RESTWebApiCodeFirst.Entities.ComponentTypes", "ComponentTypes")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturers");

                    b.Navigation("ComponentTypes");
                });

            modelBuilder.Entity("RESTWebApiCodeFirst.Entities.PCComponents", b =>
                {
                    b.HasOne("RESTWebApiCodeFirst.Entities.Components", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RESTWebApiCodeFirst.Entities.PCs", "PCs")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PCs");
                });

            modelBuilder.Entity("RESTWebApiCodeFirst.Entities.ComponentManufacturers", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("RESTWebApiCodeFirst.Entities.ComponentTypes", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("RESTWebApiCodeFirst.Entities.Components", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("RESTWebApiCodeFirst.Entities.PCs", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
